Enhance start server
KinderCorp/battleship-back pull request #16
Opened 2022-11-24 12:04 UTC by FlavianEng

2022-11-24 12:04 UTC, FlavianEng commented
Task linked: [CU-3aybt6n Enhance start server](https://app.clickup.com/t/3aybt6n)

2022-11-24 12:24 UTC, MaximeWrlz requested changes

2022-11-24 12:24 UTC, MaximeWrlz commented on src/domains/character/character.controller.ts
> +          message: 'Fail to insert boat.',
Replace "boat" by "character"

2022-11-24 12:24 UTC, MaximeWrlz commented on src/domains/game/game.controller.ts
> +          message: 'Fail to insert boat.',
Replace "boat" by "game"

2022-11-24 12:24 UTC, MaximeWrlz commented on src/domains/level/level.controller.ts
> +          message: 'Fail to insert boat.',
Replace "boat" by "level"

2022-11-24 12:24 UTC, MaximeWrlz commented on src/domains/media-with-theme/media-with-theme.controller.ts
> +          message: 'Fail to insert boat.',
Replace "boat" by "media with theme"

2022-11-24 12:24 UTC, MaximeWrlz commented on src/domains/media/media.controller.ts
> +          message: 'Fail to insert boat.',
Replace "boat" by "media"

2022-11-24 12:24 UTC, MaximeWrlz commented on src/domains/theme/theme.controller.ts
> +          message: 'Fail to insert boat.',
Replace "boat" by "theme"

2022-11-24 12:24 UTC, MaximeWrlz commented on src/domains/user/user.controller.ts
> +          message: 'Fail to insert boat.',
Replace "boat" by "user"

2022-11-24 12:24 UTC, MaximeWrlz commented on src/domains/weapon/weapon.controller.ts
> +          message: 'Fail to insert boat.',
Replace "boat" by "weapon"

2022-11-24 13:21 UTC, MaximeWrlz submitted a review, later dismissed

2022-11-24 13:26 UTC, MaximeWrlz approved these changes

2022-11-24 13:29 UTC, MASBERNATQ approved these changes

2022-11-24 13:30 UTC, merged

2023-08-20 17:35 UTC, FlavianEng commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/KinderCorp/battleship-back/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-08-23 22:11 UTC, FlavianEng commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/KinderCorp/battleship-back/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-08-24 06:48 UTC, FlavianEng commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/KinderCorp/battleship-back/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: