Cu 3c0r44m setup sockets
KinderCorp/battleship-back pull request #17
Opened 2022-11-24 14:05 UTC by MaximeWrlz

2022-11-24 14:06 UTC, FlavianEng commented
Task linked: [CU-3c0r44m Setup Sockets](https://app.clickup.com/t/3c0r44m)

2022-11-24 14:08 UTC, FlavianEng submitted a review, later dismissed

2022-11-24 14:08 UTC, FlavianEng commented on src/engine/gateways/gameGateway.ts
> +      this.logger.log('Connected');
Isn't async ?

2022-11-24 14:08 UTC, FlavianEng commented on src/engine/gateways/gameGateway.ts
> +      this.logger.log('Connected');
```suggestion
      this.logger.log(`Socket ${socket.id} connected`);
```

2022-11-24 14:10 UTC, FlavianEng commented on src/engine/gateways/gameGateway.ts
> +      this.logger.log('Connected');
Maxime > No, it's not necessary

2022-11-24 14:12 UTC, FlavianEng requested changes

2022-11-24 14:12 UTC, FlavianEng commented on src/engine/gateways/gameGateway.ts
> +import { Server } from 'socket.io';
```suggestion
import { Server as SocketServer } from 'socket.io';
```

2022-11-24 14:12 UTC, FlavianEng commented on src/engine/gateways/gameGateway.ts
> +    this.server.on('connection', (socket) => {
```suggestion
  public socketServer: SocketServer;

  public onModuleInit() {
    this.socketServer.on('connection', (socket) => {
```

2022-11-24 14:15 UTC, FlavianEng approved these changes

2022-11-24 14:17 UTC, ManonFargues approved these changes

2022-11-24 14:17 UTC, merged

2023-08-20 17:35 UTC, FlavianEng commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/KinderCorp/battleship-back/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-08-23 22:11 UTC, FlavianEng commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/KinderCorp/battleship-back/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-08-24 06:48 UTC, FlavianEng commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/KinderCorp/battleship-back/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: