Cu 3c0tr1r fix boat entity
KinderCorp/battleship-back pull request #18
Opened 2022-11-25 10:45 UTC by MaximeWrlz

2022-11-25 10:45 UTC, FlavianEng commented
Task linked: [CU-3c0tr1r Fix Boat entity](https://app.clickup.com/t/3c0tr1r)

2022-11-25 10:50 UTC, ManonFargues submitted a review, later dismissed

2022-11-25 10:58 UTC, FlavianEng requested changes

2022-11-25 10:58 UTC, FlavianEng commented on bin/fixtures-load.sh
>          ./src/fixtures/media.yml \
Don't we remove media too ?

2022-11-25 10:58 UTC, FlavianEng commented on src/domains/character/character.entity.ts
>    public media!: number;
Don't we remove this field ?

2022-11-25 10:58 UTC, FlavianEng commented on src/modules/domain.module.ts
>  import MediaService from '@media/media.service';
Don't we remove this entity ?

2022-11-25 10:58 UTC, FlavianEng commented on src/shared/entities.export.ts
>  import Media from '@media/media.entity';
Don't we remove this entity ?

2022-11-25 10:58 UTC, FlavianEng commented on tsconfig.json
>        "@media/*": ["src/domains/media/*"],
Don't we remove media ?

2022-11-25 11:27 UTC, FlavianEng approved these changes

2022-11-25 11:49 UTC, DrakenLine approved these changes

2022-11-25 11:50 UTC, merged

2023-08-20 17:35 UTC, FlavianEng commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/KinderCorp/battleship-back/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-08-23 22:11 UTC, FlavianEng commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/KinderCorp/battleship-back/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-08-24 06:47 UTC, FlavianEng commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/KinderCorp/battleship-back/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: