Cu 39w8aku rename postgressql
KinderCorp/battleship-back pull request #8
Opened 2022-11-10 10:23 UTC by MaximeWrlz

2022-11-10 10:31 UTC, ManonFargues submitted a review, later dismissed

2022-11-10 10:40 UTC, FlavianEng requested changes

2022-11-10 10:40 UTC, FlavianEng commented on src/modules/app.module.ts
> +import { LoggerInterceptor } from '../interceptors/logger/logger.interceptor';
Add an alias path

2022-11-10 10:51 UTC, FlavianEng approved these changes

2022-11-10 10:52 UTC, ManonFargues approved these changes

2022-11-10 10:54 UTC, merged

2023-08-20 17:36 UTC, FlavianEng commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/KinderCorp/battleship-back/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-08-23 22:12 UTC, FlavianEng commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/KinderCorp/battleship-back/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-08-24 06:48 UTC, FlavianEng commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/KinderCorp/battleship-back/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: